typography_spectrum: 0.21597852810820803
color:
  brandStrength: 0.9476418303363577
  lightness: 0.5150001048003462
  saturation: 0.6419046918714953
  rhythmicContrast: 0.32339985160055656
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#CD9AF7'
    - '#51307F'
    - '#AAD8E4'
github: true
layout_spectrum: 0.3225723085688003
analytics:
  facebook: '413880438950956'
  google: UA-17071199-1
author:
  url: 'https://eightcorners.co'
  name: Gretchen Oris-Chong
  email: hello@eightcorners.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c14d990-61e4-41e3-9ee2-64ce1695d349.png
name: eight corners blog
url: 'https://blog.eightcorners.co'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: home
    url: 'http://eightcorners.co'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5a2595c-c7b1-40da-acc3-3a44d3b9e55f.png
title: createrati
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fabf300-d35d-42ba-9373-0d86e297cf52.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fabf300-d35d-42ba-9373-0d86e297cf52.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Branding, design & business, fueled by travel & flat whites.'
purpose:
  - type: external
    url: 'http://take.thebrandtour.com/library'
    label: Free Resource Library for Design & Branding
  - type: external
    url: 'http://createrati.com'
    label: Join The Createrati Community
